[2024-08-18T07:11:42.394+0000] {processor.py:186} INFO - Started process (PID=71) to work on /opt/airflow/dags/xchange_rate_pipeline.py
[2024-08-18T07:11:42.398+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/xchange_rate_pipeline.py for tasks to queue
[2024-08-18T07:11:42.420+0000] {logging_mixin.py:190} INFO - [2024-08-18T07:11:42.417+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/xchange_rate_pipeline.py
[2024-08-18T07:11:42.621+0000] {logging_mixin.py:190} INFO - [2024-08-18T07:11:42.602+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/xchange_rate_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/xchange_rate_pipeline.py", line 7, in <module>
    from clean_data import clean_data
ModuleNotFoundError: No module named 'clean_data'
[2024-08-18T07:11:42.627+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/xchange_rate_pipeline.py
[2024-08-18T07:11:42.730+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/xchange_rate_pipeline.py took 0.361 seconds
